# Generated by Django 6.0.3 on 2026-03-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Züccaciye Mağazası', max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('working_hours', models.CharField(blank=True, help_text='Örn: Hafta içi: 09:00 - 20:00', max_length=255, null=True)),
                ('map_embed_url', models.TextField(blank=True, help_text="Google Maps'ten alınan iframe linki", null=True)),
            ],
            options={
                'verbose_name_plural': 'Store Information',
            },
        ),
    ]
